name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: build-test, platform: linux/amd64, os: ubuntu-latest, artifact: linux-amd64},
          {name: build-test, platform: windows/amd64, os: windows-latest, artifact: windows-amd64},
          {name: build-test, platform: darwin/amd64, os: macos-latest, artifact: macos-amd64},
          {name: build-test, platform: darwin/arm64, os: macos-latest, artifact: macos-arm64}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
      - name: Package macOS application
        if: matrix.build.platform == 'darwin/amd64' || matrix.build.platform == 'darwin/arm64'
        run: |
          ls -la build/bin/
          chmod +x build/bin/*.app/Contents/MacOS/*
          ditto -c -k --keepParent "build/bin/build-test.app" "build/bin/${{ matrix.build.artifact }}.zip"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.artifact }}
          path: build/bin/${{ matrix.build.name }}*
