name: Wails Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu2404:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          go-version: '1.22'
          package: false # Do not try to upload to github

  macos15arm64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: darwin/arm64
          sign: false
          go-version: '1.22'
          package: false # Do not try to upload to github
      - name: List build directory contents
        run: ls -R ./build/bin

  macos15amd64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: darwin/amd64
          sign: false
          go-version: '1.22'
          package: false # Do
      - name: List build directory contents
        run: ls -R ./build/bin

  windows2025:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: 'false'
          go-version: '1.22'
          package: false # Do not try to upload to github
