name: Wails build

on:
  push:
    branches: [ main ]
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'Suspects'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'Suspects'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'Suspects'
            platform: 'darwin/amd64'
            os: 'macos-latest'
          - name: 'Suspects'
            platform: 'darwin/arm64'
            os: 'macos-latest'
          # - name: 'Suspects'
          #   platform: 'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.22'

      - name: List build directory contents
        run: |
          echo "Listing contents of the build directory:"
          if [ "${{ runner.os }}" == "Windows" ]; then
            Get-ChildItem -Path . -Recurse
          else
            ls -R
          fi
        shell: bash
