name: Wails macOS Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build macOS (amd64 and arm64)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build for macOS amd64
        uses: dAppServer/wails-build-action@main
        with:
          build-name: myWailsApp
          build-platform: darwin/amd64
          wails-version: latest
          go-version: 1.23
          node-version: 22.11

      - name: Rename amd64 app
        run: |
          if [ -d "./build/bin/myWailsApp.app" ]; then
            mv ./build/bin/myWailsApp.app ./build/bin/myWailsApp-darwin-amd64.app
          fi

      - name: Build for macOS arm64
        uses: dAppServer/wails-build-action@main
        with:
          build-name: myWailsApp
          build-platform: darwin/arm64
          wails-version: latest
          go-version: 1.23
          node-version: 22.11

      - name: Rename arm64 app
        run: |
          if [ -d "./build/bin/myWailsApp.app" ]; then
            mv ./build/bin/myWailsApp.app ./build/bin/myWailsApp-darwin-arm64.app
          fi
