name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {platform: linux/amd64, os: ubuntu-latest, artifact: linux-amd64},
          {platform: windows/amd64, os: windows-latest, artifact: windows-amd64},
          {platform: darwin/amd64, os: macos-latest, artifact: macos-amd64},
          {platform: darwin/arm64, os: macos-latest, artifact: macos-arm64}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: build-test-${{ env.PLATFORM_SAFE }} # For the executable inside
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
      - name: Set platform variable
        id: platform_variable
        run: |
          echo "PLATFORM_SAFE=$(echo "${{ matrix.build.platform }}" | sed 's/\//-/g')" >> $GITHUB_ENV
      - name: Package macOS application
        if: matrix.build.platform == 'darwin/amd64' || matrix.build.platform == 'darwin/arm64'
        run: |
          APP_NAME="build-test" # The .app bundle name is ALWAYS build-test.app
          chmod +x build/bin/${APP_NAME}.app/Contents/MacOS/${APP_NAME}-${{ env.PLATFORM_SAFE }} # Correct chmod path!
          ditto -c -k --keepParent "build/bin/${APP_NAME}.app" "build/bin/${{ matrix.build.artifact }}.zip" # Correct ditto path!
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-test-${{ env.PLATFORM_SAFE }}-${{ matrix.build.artifact }}
          path: build/bin/${{ matrix.build.artifact }}.zip
