name: Wails Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu2404:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          package: false # Do not try to upload to github

  macos15arm64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: darwin/arm64
          sign: false
          # sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          # sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          # sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          # sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          # sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          # sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          # sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
          package: false # Do not try to upload to github

  macos15amd64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: darwin/amd64
          sign: false
          # sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          # sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          # sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          # sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          # sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          # sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          # sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}
          package: false # Do not try to upload to github

  windows2025:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: 'false'
          package: false # Do not try to upload to github
