name: Wails macOS Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build macOS (amd64 and arm64)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build for macOS amd64
        uses: dAppServer/wails-build-action@main
        with:
          build-name: myWailsApp
          build-platform: darwin/amd64
          wails-version: latest
          go-version: 1.23
          node-version: 22.11

      - name: Debug amd64 build output
        run: |
          echo "Listing build directory contents:"
          ls -la build/
          echo "Listing bin directory contents:"
          ls -la build/bin/
          echo "Checking for .app bundle:"
          find ./build -name "*.app" -type d

      - name: Rename amd64 app
        run: |
          APP_PATH=$(find ./build -name "*.app" -type d | head -n 1)
          if [ -n "$APP_PATH" ]; then
            echo "Found app bundle at: $APP_PATH"
            TARGET_NAME=$(basename "$APP_PATH" | sed 's/\.app$/-darwin-amd64.app/')
            TARGET_PATH="./build/bin/$TARGET_NAME"
            echo "Renaming to: $TARGET_PATH"
            mkdir -p ./build/bin
            mv "$APP_PATH" "$TARGET_PATH"
          else
            echo "No .app bundle found!"
            exit 1
          fi

      - name: Build for macOS arm64
        uses: dAppServer/wails-build-action@main
        with:
          build-name: myWailsApp
          build-platform: darwin/arm64
          wails-version: latest
          go-version: 1.23
          node-version: 22.11

      - name: Debug arm64 build output
        run: |
          echo "Listing build directory contents:"
          ls -la build/
          echo "Listing bin directory contents:"
          ls -la build/bin/
          echo "Checking for .app bundle:"
          find ./build -name "*.app" -type d

      - name: Rename arm64 app
        run: |
          APP_PATH=$(find ./build -name "*.app" -type d | head -n 1)
          if [ -n "$APP_PATH" ]; then
            echo "Found app bundle at: $APP_PATH"
            TARGET_NAME=$(basename "$APP_PATH" | sed 's/\.app$/-darwin-arm64.app/')
            TARGET_PATH="./build/bin/$TARGET_NAME"
            echo "Renaming to: $TARGET_PATH"
            mkdir -p ./build/bin
            mv "$APP_PATH" "$TARGET_PATH"
          else
            echo "No .app bundle found!"
            exit 1
          fi

      - name: Final directory listing
        run: |
          echo "Final build/bin contents:"
          ls -la build/bin/
