name: Wails Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          package: false # Do not try to upload to github

  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails
          build-platform: linux/arm64
          wails-build-webview2: "embed"
          package: false # Do not try to upload to github

  macos-arm64:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: build-test
          build-platform: darwin/arm64
          sign: false
          package: false # Do not try to upload to github

  macos-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: build-test
          build-platform: darwin/amd64
          sign: false
          package: false

  macos-universal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: build-test
          build-platform: darwin/universal
          sign: false
          package: false

  windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: false
          package: false # Do not try to upload to github

  windows-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: wails.exe
          build-platform: windows/arm64
          wails-build-webview2: "embed"
          nsis: false
          package: false # Do not try to upload to github
